# Generated by Django 2.0.7 on 2020-04-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inv_no', models.CharField(max_length=15)),
                ('Status', models.CharField(max_length=10)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('complete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=50)),
                ('RCP', models.CharField(max_length=5)),
                ('RSP', models.CharField(max_length=5)),
                ('Bal', models.CharField(max_length=5)),
                ('Order', models.CharField(max_length=5)),
                ('D_Qty', models.CharField(max_length=5)),
                ('D_FP', models.CharField(max_length=5)),
                ('UAD', models.CharField(max_length=5)),
                ('Remark', models.CharField(max_length=50)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('Invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='User_action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='thread',
            name='first',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
