# Generated by Django 2.2 on 2020-04-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=10)),
                ('AccOpenDate', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=10)),
                ('CreditLimit', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=10)),
                ('BusinessNature', models.CharField(max_length=10)),
                ('Code', models.CharField(max_length=10)),
                ('CompanyCategory', models.CharField(max_length=10)),
                ('Attention', models.CharField(max_length=10)),
                ('Phone1', models.CharField(max_length=10)),
                ('Area', models.CharField(max_length=10)),
                ('Agent', models.CharField(max_length=10)),
                ('CreditTerm', models.CharField(max_length=10)),
                ('AddTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
