# Generated by Django 2.2 on 2020-04-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_outlet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=20)),
                ('Barcodes', models.CharField(max_length=20)),
                ('Catergory', models.CharField(max_length=50)),
                ('PackSize', models.CharField(max_length=10)),
                ('CtnQty', models.CharField(max_length=10)),
                ('RCP', models.CharField(max_length=10)),
                ('RSP', models.CharField(max_length=10)),
                ('RetailerMargin', models.CharField(max_length=10)),
                ('FastPay', models.CharField(max_length=10)),
                ('UlkPurchase', models.CharField(max_length=10)),
            ],
        ),
    ]
