# Generated by Django 2.2 on 2020-04-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
    ]
