# Generated by Django 2.2 on 2020-04-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200417_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='AccOpenDate',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='Address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='Agent',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='Area',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='Attention',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='BusinessNature',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='Code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='CompanyCategory',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='CompanyName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='CreditTerm',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='Email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='Phone1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='Status',
            field=models.CharField(max_length=15),
        ),
    ]
