# Generated by Django 2.2 on 2020-04-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200417_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Catergory',
            new_name='Name',
        ),
    ]
